# Generated by Django 4.1.4 on 2022-12-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='kategory',
            new_name='kategori',
        ),
    ]
