# Generated by Django 4.1.4 on 2022-12-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0009_alter_berita_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.CharField(max_length=100),
        ),
    ]
