# Generated by Django 4.1.4 on 2022-12-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0010_alter_berita_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='image',
        ),
    ]
